---
title: "Figures"
author: "Anne Hoffrichter, Eric Poisel, Lea Zillich"
date: "2022/02/17"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts=list(width.cutoff=80),tidy=TRUE, fig.asp=0.5, fig.width=12, warning = FALSE)
```

```{r loadLibraries, message=FALSE, warning=FALSE}
library(Seurat)
library(ggplot2)
library(cowplot)
library(openxlsx)
library(dplyr)
library(readxl)
library(fgsea)
library(msigdb)
library(enrichR)
library(msigdbr)
library(org.Hs.eg.db)
library(tidyverse)
library(patchwork)
library(GO.db)
library(ggpubr)
library(pheatmap)
set.seed(42)
```

- Import integrated object
```{r importObject}
sc <- readRDS(file = "path/to/seurat_objects/LIS1_integrated.rds")
```

```{r normalize data}
# Set Idents to clusters names
Idents(sc) <- "cell_types"

# Normalize and scale RNA assay
sc <- NormalizeData(sc, assay = "RNA")
sc <- FindVariableFeatures(sc, selection.method = "vst", assay = "RNA")
sc <- ScaleData(sc, features = rownames(sc), assay = "RNA")
```

- Figure 2A
```{r normalize data}
DimPlot(sc, reduction = "umap", split.by = "replicate")
```

- Figure 2B
```{r dotplot markers}
genes <- c("TOP2A","TPX2","MKI67","CTNNB1","CDH2", "FABP7", "HES1","HES4","HES5", "SOX2", "SOX4", "VIM", "NES", "ANXA5", "PTPRZ1", "FABP5","C1orf61", "OTX2", "PAX6", "EMX2", "SFRP1", "NEUROD1","EOMES",  "ELAVL4", "TBR1", "STMN1", "DCX", "MAP2", "DLX1", "DLX2", "SLC32A1", "ARX", "SST", "ROBO2", "LMX1B","EN1", "EN2", "MOXD1", "S100B")

sc@active.ident <- factor(sc@active.ident, 
                            levels=c("NES",
                                     "CyP",
                                     "RG",
                                     "PP",
                                     "IP",
                                     "dFB-N", 
                                     "vFB-N", 
                                     "IN", 
                                     "MB-N", 
                                     "G"))


DotPlot(object = sc, features = genes,assay ="RNA", dot.scale = 5) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(axis.text.y = element_text(size=6)) + 
  theme(axis.text.x = element_text(size=6)) + 
  theme(text=element_text(size = 8)) + 
  theme(aspect.ratio =0.5)
```

- Figure 2E

## Violin plots GO terms 

```{r define function, warning=FALSE, results='hide'}
add_GO_perc <- function(data, GO_term){
  go_id = GOID(GOTERM[Term(GOTERM) == GO_term])
  allegs <- get(go_id, org.Hs.egGO2ALLEGS)
  genes <- unlist(mget(allegs, org.Hs.egSYMBOL))
  genes <- unique(genes)        
  genes <- genes[genes %in% rownames(data)]
  PercentageFeatureSet(object=data, features=genes, col.name = GO_term)
}  
```

```{r subset sc object, warning=FALSE, results='hide'}
DefaultAssay(sc) <- "RNA"
sc@meta.data$cluster_condition <- paste0(sc@meta.data$condition,sc@meta.data$seurat_clusters)
Idents(sc) <- "cluster_condition"

# Comparison only in Severe vs. Ctrl, cluster 3 = PP, cluster 0 = RG
sc2 <- subset(sc, idents=c("Severe3","Ctrl0"))
Idents(sc2) <- "cell_types"
```

## RG and PP clusters
```{r GO plots, warning=FALSE, results='hide'}
GO_terms <- c("neuron differentiation","generation of neurons","neuron fate commitment","regulation of neuron differentiation")
for(i in seq_along(GO_terms)){
  sc2 <- add_GO_perc(sc2, GO_terms[i])
}

titles <- c("neuron differentiation","generation of neurons","neuron fate commitment","regulation of neuron differentiation")
GO_terms_no_space <- str_replace_all(GO_terms, " ", ".")
plots <- map2(GO_terms_no_space, titles, ~VlnPlot(sc2, features=.x, split.by = "cell_types", pt.size=0.1)+ ggtitle(.y))

wil_t <- list()
for(i in GO_terms_no_space){
  df <- data.frame(GO=sc2[[i]], clusters=sc2$cell_types)
  wil_t[[i]] <- wilcox.test(x=filter(df, clusters=="RG")[,1], y=filter(df, clusters=="PP")[,1])
}

# p-values 
wil_t$neuron.differentiation$p.value #2.520929e-15
wil_t$generation.of.neurons$p.value #3.649961e-14
wil_t$neuron.fate.commitment$p.value #3.625523e-61
wil_t$regulation.of.neuron.differentiation$p.value #1.506357e-190

plots[[1]] <- plots[[1]]+
  annotate("text", x=1.5, y=max(sc2[[GO_terms_no_space[1]]])+max(sc2[[GO_terms_no_space[1]]])*0.1, label="***", size=10)+
  ylim(min(sc2[[GO_terms_no_space[1]]])-min(sc2[[GO_terms_no_space[1]]])*0.15,max(sc2[[GO_terms_no_space[1]]])+max(sc2[[GO_terms_no_space[1]]])*0.15)
plots[[2]] <- plots[[2]]+
  annotate("text", x=1.5, y=max(sc2[[GO_terms_no_space[2]]])+max(sc2[[GO_terms_no_space[2]]])*0.1, label="***", size=10)+
  ylim(min(sc2[[GO_terms_no_space[2]]])-min(sc2[[GO_terms_no_space[2]]])*0.15,max(sc2[[GO_terms_no_space[2]]])+max(sc2[[GO_terms_no_space[2]]])*0.15)
plots[[3]] <- plots[[3]]+
  annotate("text", x=1.5, y=max(sc2[[GO_terms_no_space[3]]])+max(sc2[[GO_terms_no_space[3]]])*0.1, label="***", size=10)+
  ylim(min(sc2[[GO_terms_no_space[3]]])-min(sc2[[GO_terms_no_space[3]]])*0.15,max(sc2[[GO_terms_no_space[3]]])+max(sc2[[GO_terms_no_space[3]]])*0.15)
plots[[4]] <- plots[[4]]+
  annotate("text", x=1.5, y=max(sc2[[GO_terms_no_space[4]]])+max(sc2[[GO_terms_no_space[4]]])*0.1, label="***", size=10)+
  ylim(min(sc2[[GO_terms_no_space[4]]])-min(sc2[[GO_terms_no_space[4]]])*0.15,max(sc2[[GO_terms_no_space[4]]])+max(sc2[[GO_terms_no_space[4]]])*0.15)

vln <- wrap_plots(plots, guides="collect", nrow=1)& 
  theme(axis.title.x=element_blank(), axis.text.y=element_text(size=18), plot.title = element_text(size=14), legend.text = element_text(size=14), axis.title.y=element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank())&
  ylab("Proportion of feature set")&
  scale_fill_manual(values=c("#DA5B51", "#00A5AA"), labels=c("RG","PP"))

```

- Figure 4C

# WNT gene heatmap in CyP cluster 

```{r define stars function, warning=FALSE}
stars_gen <- function(x){
  stars <- c( "***", "**", "*","")
  vec <- c(0, 0.001, 0.01, 0.05,1.01)
  i <- findInterval(x, vec)
  stars[i]
}
```

# Generate DE gene lists for CyP cluster
```{r DE 1, results='hide', warning=FALSE, results='hide'}
Idents(sc)<- "cluster_condition"

# Cluster 1 are CyP cells
markers_Mild_vs_Ctrl_1 <- FindMarkers(sc,ident.1 = "Mild1" , ident.2 = "Ctrl1", min.pct = 0.25,assay = "RNA", logfc.threshold = 0)
markers_Moderate_vs_Ctrl_1 <- FindMarkers(sc,ident.1 = "Moderate1" , ident.2 = "Ctrl1", min.pct = 0.25,assay = "RNA", logfc.threshold = 0)
markers_Severe_vs_Ctrl_1 <- FindMarkers(sc,ident.1 = "Severe1" , ident.2 = "Ctrl1", min.pct = 0.25,assay = "RNA", logfc.threshold = 0)
```

# Specify marker genes
```{r gene lists, results='hide', warning=FALSE}
list <- c("AXIN1","BCL9","BCL9L","CBY1","CSNK1E","CTDNEP1","CTNNB1","DACT3","DISC1","DIXDC1","DKK1","DVL1","DVL1P1","DVL2",    "DVL3","EDA","EDN1","EDNRA","EDNRB","EXT1","FGF2","FGF9","FOXD1","FOXO1","FOXO3","FRAT1" ,"FRZB","FZD1","FZD10","FZD2","FZD3" ,   "FZD4","FZD5","FZD6","FZD7","FZD8","FZD9","GPC3","HESX1","ISL1","JUP","KLF4","LATS2","LEF1","LRP5","LRP6","LRRK2","NR4A2","PLPP3",   "PTEN" ,"PYGO1","PYGO2","RARG","RECK","RSPO2","RSPO3","RYK","SDC1","SFRP1","SFRP2","SFRP4","SFRP5","SHH","SIAH1","SIAH2","SOST",    "SOSTDC1","SOX9","STK3" , "STK4","TCF7","TCF7L1","TCF7L2","WNT1" ,"WNT10A","WNT10B","WNT11" ,"WNT16" ,"WNT2","WNT2B","WNT3",    "WNT3A" ,"WNT4","WNT5A","WNT5B","WNT6","WNT7A","WNT7B","WNT8A","WNT8B","WNT9A","WNT9B","YAP1")
```

# Generate heatmap

```{r heatmapsWntcanonicalCyP results='hide', warning=FALSE}

list_Mild_vs_Ctrl_1 <- markers_Mild_vs_Ctrl_1[list,c(2,5)][complete.cases(markers_Mild_vs_Ctrl_1[list,c(2,5)]),]
colnames(list_Mild_vs_Ctrl_1) <- paste0("Mild_",colnames(list_Mild_vs_Ctrl_1))
list_Moderate_vs_Ctrl_1 <- markers_Moderate_vs_Ctrl_1[list,c(2,5)][complete.cases(markers_Moderate_vs_Ctrl_1[list,c(2,5)]),]
colnames(list_Moderate_vs_Ctrl_1) <- paste0("Moderate_",colnames(list_Moderate_vs_Ctrl_1))
list_Severe_vs_Ctrl_1 <- markers_Severe_vs_Ctrl_1[list,c(2,5)][complete.cases(markers_Severe_vs_Ctrl_1[list,c(2,5)]),]
colnames(list_Severe_vs_Ctrl_1) <- paste0("Severe_",colnames(list_Severe_vs_Ctrl_1))

# Subset shared genes
list_Mild_vs_Ctrl_1 <- list_Mild_vs_Ctrl_1[rownames(list_Mild_vs_Ctrl_1) %in% rownames(list_Severe_vs_Ctrl_1),]
list_Moderate_vs_Ctrl_1 <- list_Moderate_vs_Ctrl_1[rownames(list_Moderate_vs_Ctrl_1) %in% rownames(list_Severe_vs_Ctrl_1),]
cluster1 <- cbind(list_Mild_vs_Ctrl_1,list_Moderate_vs_Ctrl_1,list_Severe_vs_Ctrl_1)


# Select log2FC values
cluster1_log2FC <- as.matrix(cluster1[,c(1,3,5)])
colnames(cluster1_log2FC) <- c("Mild","Moderate","Severe")

# Generate information on significance
cluster1_p <- cluster1[,c(2,4,6)]
colnames(cluster1_p) <- c("Mild","Moderate","Severe")
for(i in colnames(cluster1_p)){
cluster1_p[,i] <- stars_gen(cluster1_p[,i])}
cluster1_p <- as.matrix(cluster1_p)

# Plot heatmap
pheatmap(cluster1_log2FC, breaks=seq(-1.5, 1.5, length.out=100),color = colorRampPalette(c("blue","white","red"))(100),cluster_rows = F,cluster_cols = F,fontsize = 16,display_numbers = cluster1_p, angle_col = 45,cellwidth = 20,cellheight = 20)
```

- Extended Data Figure 3A

```{r by condition, warning=FALSE, results='hide'}
Idents(sc) <- "cell_types"
DimPlot(sc, reduction = "umap", split.by = "condition", group.by = "cell_types") + ggtitle(NULL)
```