---
title: "Preprocessing Moderate"
author: "Anne Hoffrichter, Eric Poisel, Lea Zillich"
date: "2021/11/23"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts=list(width.cutoff=80),tidy=TRUE, fig.asp=0.5, fig.width=12, warning = FALSE)
```

```{r loadLibraries, message=FALSE, warning=FALSE}
library(Seurat)
library(ggplot2)
library(cowplot)
library(openxlsx)
set.seed(42)
```

## Moderate

- Set up Moderate object   
```{r setUpModerateSeuratObject}
Moderate1.rawdata <- Read10X("path/to/raw_data/P3/filtered_feature_bc_matrix/")
Moderate2.rawdata <- Read10X("path/to/raw_data/P4/filtered_feature_bc_matrix/")
Moderate1Param <- read.table("path/to/001_filter_param_P3.txt")
Moderate2Param <- read.table("path/to/001_filter_param_P4.txt")

Moderate1 <- CreateSeuratObject(counts =Moderate1.rawdata, min.cells = 3, min.features = Moderate1Param$expr_features, project = "OK")
Moderate1$replicate <- "Moderate1"
Moderate1[["percent.mt"]] <- PercentageFeatureSet(object = Moderate1, pattern = "^MT-")

Moderate2 <- CreateSeuratObject(counts = Moderate2.rawdata, min.cells = 3, min.features = Moderate2Param$expr_features, project = "OK")
Moderate2$replicate <- "Moderate2"
Moderate2[["percent.mt"]] <- PercentageFeatureSet(object = Moderate2, pattern = "^MT-")
```

- Filter Moderate cells
  - by total counts
  - by percent of mitochondrial genes expressed
```{r filterModerateCells, message=FALSE}
Moderate1 <- subset(x=Moderate1, subset= colSums(Moderate1)>Moderate1Param$total_counts & percent.mt <Moderate1Param$MT)
Moderate2 <- subset(x=Moderate2, subset= colSums(Moderate2)>Moderate2Param$total_counts & percent.mt <Moderate2Param$MT)
```

- Additional QC steps 
  - SCTransform and add cell cycle annotation
  - remove doublets
  - integrate objects and generate clusters 
```{r cellCycle, message=FALSE}

#### Moderate1 ####

# SCTransform
Moderate1 <- SCTransform(
  Moderate1,
  assay = 'RNA',
  new.assay.name = 'SCT',
  vars.to.regress = c('percent.mt', 'nFeature_RNA', 'nCount_RNA'),
  verbose = F
)

# perform cell cycle scoring
Moderate1<- CellCycleScoring(
  Moderate1,
  s.features = cc.genes$s.genes,
  g2m.features = cc.genes$g2m.genes,
  assay = 'SCT',
  set.ident = TRUE
)

Moderate1$CC.Difference <- Moderate1$S.Score - Moderate1$G2M.Score

# second SCTransform step 
Moderate1 <- SCTransform(
  Moderate1,
  assay = 'RNA',
  new.assay.name = 'SCT',
  vars.to.regress = c('percent.mt', 'nFeature_RNA', 'nCount_RNA', 'CC.Difference'),
  verbose = F
)

#### Moderate2 ####

# SCTransform
Moderate2 <- SCTransform(
  Moderate2,
  assay = 'RNA',
  new.assay.name = 'SCT',
  vars.to.regress = c('percent.mt', 'nFeature_RNA', 'nCount_RNA'),
  verbose=FALSE
)

# perform cell cycle scoring
Moderate2<- CellCycleScoring(
  Moderate2,
  s.features = cc.genes$s.genes,
  g2m.features = cc.genes$g2m.genes,
  assay = 'SCT',
  set.ident = TRUE
)

Moderate2$CC.Difference <- Moderate2$S.Score - Moderate2$G2M.Score

# second SCTransform step 
Moderate2 <- SCTransform(
  Moderate2,
  assay = 'RNA',
  new.assay.name = 'SCT',
  vars.to.regress = c('percent.mt', 'nFeature_RNA', 'nCount_RNA', 'CC.Difference'),
  verbose = F
)
```

```{r DoubletRemoval, message=FALSE}
suppressMessages(require(DoubletFinder))

# Estimated number of expected multiplets based on the number of analyzed cells (see https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_01_qc.html)

#Moderate1: around 5500 cells prior to QC -> 4.6% doublets
nExp1 <- round(ncol(Moderate1) * 0.046)
#Moderate2: around 3000 cells prior to QC -> 2.3% doublets
nExp2 <- round(ncol(Moderate2) * 0.023)

# Determine dimensionality of the dataset for doublet estimation 
Moderate1 <- RunPCA(Moderate1, verbose = FALSE)
Moderate2 <- RunPCA(Moderate2, verbose = FALSE)
ElbowPlot(Moderate1) # 15 PCs
ElbowPlot(Moderate2) # 15 PCs
```

```{r parameterOptimization, message=FALSE, include=FALSE}
sweep.res1 <- paramSweep_v3(Moderate1,sct = TRUE, PCs = 1:15) 
sweep.stats1 <- summarizeSweep(sweep.res1, GT = FALSE) 
bcmvn1 <- find.pK(sweep.stats1) 
barplot(bcmvn1$BCmetric, names.arg = bcmvn1$pK, las=2)
# maximum at pK = 0.06

sweep.res2 <- paramSweep_v3(Moderate2,sct = TRUE, PCs = 1:15) 
sweep.stats2 <- summarizeSweep(sweep.res2, GT = FALSE) 
bcmvn2 <- find.pK(sweep.stats2) 
barplot(bcmvn2$BCmetric, names.arg = bcmvn2$pK, las=2)
# maximum at pK = 0.22
```

```{r findDoublets1, message=FALSE, include = FALSE}
Moderate1 <- doubletFinder_v3(Moderate1, pN = 0.25, pK = 0.06, nExp = nExp1, PCs = 1:15, sct = T)
```

```{r removeDoublets1, message=FALSE}
DF.name1 = colnames(Moderate1@meta.data)[grepl("DF.classification", colnames(Moderate1@meta.data))]
cowplot::plot_grid(ncol = 2, DimPlot(Moderate1, group.by = "orig.ident") + NoAxes(), 
    DimPlot(Moderate1, group.by = DF.name1) + NoAxes())
VlnPlot(Moderate1, features = "nFeature_RNA", group.by = DF.name1, pt.size = 0.1)
Moderate1 = Moderate1[, Moderate1@meta.data[, DF.name1] == "Singlet"]
```

```{r findDoublets2, message=FALSE, include = FALSE}
Moderate2 <- doubletFinder_v3(Moderate2, pN = 0.25, pK = 0.22, nExp = nExp2, PCs = 1:15, sct = T)
```

```{r removeDoublets2, message=FALSE}
DF.name2 = colnames(Moderate2@meta.data)[grepl("DF.classification", colnames(Moderate2@meta.data))]
cowplot::plot_grid(ncol = 2, DimPlot(Moderate2, group.by = "orig.ident") + NoAxes(), 
    DimPlot(Moderate2, group.by = DF.name2) + NoAxes())
VlnPlot(Moderate2, features = "nFeature_RNA", group.by = DF.name2, pt.size = 0.1)
Moderate2 = Moderate2[, Moderate2@meta.data[, DF.name2] == "Singlet"]
```

```{r IntegrateObjectModerate}
Moderate.list <- list(Moderate1,Moderate2)

options(future.globals.maxSize = 8000 * 1024^2)
Moderate.features <- SelectIntegrationFeatures(object.list = Moderate.list)
Moderate.list <- PrepSCTIntegration(object.list = Moderate.list, anchor.features = Moderate.features, 
    verbose = FALSE)

Moderate.anchors <- FindIntegrationAnchors(object.list = Moderate.list, normalization.method = "SCT", 
    anchor.features = Moderate.features, verbose = FALSE)
Moderate.integrated <- IntegrateData(anchorset = Moderate.anchors, normalization.method = "SCT", verbose = FALSE)

Moderate.integrated <- RunPCA(Moderate.integrated, verbose = FALSE)
Moderate.integrated <- RunUMAP(Moderate.integrated, reduction = "pca", dims = 1:50)
Moderate.integrated <- FindNeighbors(Moderate.integrated, dims = 1:50, verbose = FALSE)
Moderate.integrated <- FindClusters(Moderate.integrated, verbose = FALSE,resolution = 0.15)
```

- Save the objects after filtering and processing steps.
```{r saveObjectsAfterGeneralFilteringSteps}
saveRDS(Moderate.integrated, "path/to/seurat_objects/Moderate_integrated_sct.rds")
```

```{r sessioninfo}
sessionInfo()
```