---
title: "Integration - full experiment"
author: "Anne Hoffrichter, Eric Poisel, Lea Zillich"
date: "2022/02/11"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts=list(width.cutoff=80),tidy=TRUE, fig.asp=0.5, fig.width=12, warning = FALSE)
```

```{r loadLibraries, message=FALSE, warning=FALSE}
library(Seurat)
library(ggplot2)
library(cowplot)
library(openxlsx)
library(dplyr)
library(readxl)
set.seed(42)
```

- Import Seurat Objects
```{r ImportSeuratObjects}
Ctrl <-readRDS("path/to/seurat_objects/Ctrl_integrated_sct.rds")
Ctrl$condition <- "Ctrl"
Mild <- readRDS("path/to/seurat_objects/Mild_integrated_sct.rds")
Mild$condition <- "Mild"
Moderate <- readRDS("path/to/seurat_objects/Moderate_integrated_sct.rds")
Moderate$condition <- "Moderate"
Severe <- readRDS("path/to/seurat_objects/Severe_integrated_sct.rds")
Severe$condition <- "Severe"
```

- Integrate Seurat objects
```{r IntegrateSeuratObjects}
full.list <- list(Ctrl, Mild, Moderate, Severe)

options(future.globals.maxSize = 8000 * 1024^2)
full.features <- SelectIntegrationFeatures(object.list = full.list, nfeatures = 3000)
full.list <- PrepSCTIntegration(object.list = full.list, anchor.features = full.features, 
    verbose = FALSE)

full.anchors <- FindIntegrationAnchors(object.list = full.list, normalization.method = "SCT", 
    anchor.features = full.features, verbose = FALSE)
full.integrated <- IntegrateData(anchorset = full.anchors, normalization.method = "SCT", verbose = FALSE)

full.integrated <- RunPCA(full.integrated, verbose = FALSE)
full.integrated <- RunUMAP(full.integrated, reduction = "pca", dims = 1:50)
full.integrated <- FindNeighbors(full.integrated, dims = 1:50, verbose = FALSE)
full.integrated <- FindClusters(full.integrated, verbose = FALSE,resolution = 0.15)
```

- Proportion of cells per cluster & condition
```{r prop table}
t <- table(full.integrated$seurat_clusters, full.integrated$condition)
round(prop.table(t, margin=2)*100, digits=2)
```

- Rename replicates
```{r rename replicates}
full.integrated@meta.data$cluster_condition <- full.integrated@meta.data$replicate

full.integrated@meta.data$replicate[full.integrated@meta.data$replicate=="Ctrl1"] <- "C1"
full.integrated@meta.data$replicate[full.integrated@meta.data$replicate=="Ctrl2"] <- "C7"
full.integrated@meta.data$replicate[full.integrated@meta.data$replicate=="Mild1"] <- "P2"
full.integrated@meta.data$replicate[full.integrated@meta.data$replicate=="Mild2"] <- "P1"
full.integrated@meta.data$replicate[full.integrated@meta.data$replicate=="Moderate1"] <- "P3"
full.integrated@meta.data$replicate[full.integrated@meta.data$replicate=="Moderate2"] <- "P4"
full.integrated@meta.data$replicate[full.integrated@meta.data$replicate=="Severe1"] <- "P6"
full.integrated@meta.data$replicate[full.integrated@meta.data$replicate=="Severe2"] <- "P5"

full.integrated <- NormalizeData(full.integrated, assay ="RNA")
full.integrated <- ScaleData(full.integrated, assay ="RNA")
DefaultAssay(full.integrated) <- "RNA"
```

- Define EOMES expressing cells as separate cluster
```{r EOMES}
genes <- c("EOMES", "ELAVL3", "ELAVL4", "NEUROD1", "NHLH1")
DotPlot(object = full.integrated, features = genes,assay ="RNA")
FeaturePlot(full.integrated, features = "EOMES")

Idents(full.integrated) <- "seurat_clusters"
h1 <- subset(x = full.integrated, idents = "4",subset = EOMES > 0.25)
EOMES_cells <- colnames(h1)

levels(full.integrated@active.ident) = c(levels(full.integrated@active.ident), 9)
levels(full.integrated@meta.data$seurat_clusters) = c(levels(full.integrated@meta.data$seurat_clusters), 9)

full.integrated@active.ident[which(row.names(full.integrated@meta.data) %in%  EOMES_cells)] = 9
full.integrated@meta.data$seurat_clusters[which(row.names(full.integrated@meta.data) %in%  EOMES_cells)] = 9
```

- Rename Clusters
```{r rename clusters}
new.cluster.ids <- c("RG", "CyP", "G", "PP", "dFB-N", "NES", "vFB-N", "IN", "MB-N", "IP")
names(new.cluster.ids) <- levels(full.integrated)
full.integrated <- RenameIdents(full.integrated, new.cluster.ids)
full.integrated@meta.data$cell_types <- full.integrated@active.ident
```

- Save integrated object
```{r saveObject}
saveRDS(full.integrated,file = "path/to/seurat_objects/LIS1_integrated.rds")
```